application: abelalcazar9
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js

- url: /font
  static_dir: font

- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /diego.php
  script: diego.php

#- url: /wapp.php
  #script: wapp.php

- url: .*
  script: wapp.php