application: abelalcazar9
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js

- url: /font
  static_dir: font

- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /error.php
  script: error.php
  
- url: /mostrarcontactos.php
  script: mostrarcontactos.php
  
- url: /cgrilla.php
  script: cgrilla.php
  
- url: /agenda.php
  script: agenda.php
  
- url: /agendaBD.php
  script: agendaBD.php
  
- url: /conexion.php
  script: conexion.php
  
- url: /salir.php
  script: salir.php
  
- url: /inicio.php
  script: inicio.php

- url: /.*
  script: iniciarsesion.php